# TODO: PLOT W/ AVG. RECON, UNCERTAINTY MAP, ERROR
# TODO: PLOT PSNR VS NUM CODE VECTORS
# TODO: PLOT SSIM VS NUM CODE VECTORS
# TODO: PLOT 5 DIFFERENT RECONSTRUCTIONS FROM EACH METHOD W/ CORRESPONDING UNCERTAINTY MAP ALL ON SAME SCALE